### ISSUE TITLE
About the visualization

### ISSUE THREAD

**Issue by TitleZ99** [Paranioar/RCAR#3]
Thanks for your excellent work, I am sincerely appreciative. After reading your paper, i am waondering how to visualize the alignment weights as shown in the Figure8 and Figure9.  If you could help me with this at your convenience that would be great, thanks again for contributing such great work.
![1697690288066](https://github.com/Paranioar/RCAR/assets/96060205/7499e879-abb3-4bce-a5a4-090718fa35ee)

![1697690508432](https://github.com/Paranioar/RCAR/assets/96060205/4352f41b-db97-480a-a88c-8e848e1f33fd)

**Comment by Paranioar** [comment]
> Thanks for your excellent work, I am sincerely appreciative. After reading your paper, i am waondering how to visualize the alignment weights as shown in the Figure8 and Figure9. If you could help me with this at your convenience that would be great, thanks again for contributing such great work. ![1697690288066](https://user-images.githubusercontent.com/96060205/276489114-7499e879-abb3-4bce-a5a4-090718fa35ee.png)
> 
> ![1697690508432](https://user-images.githubusercontent.com/96060205/276489653-4352f41b-db97-480a-a88c-8e848e1f33fd.png)

I have updated related code. 
Please check it in this project. 
Thanks for the interest in our project.

**Comment by TitleZ99** [comment]
Thank you very much for your prompt reply and sharing!

**Comment by TitleZ99** [comment]
Thank you very much for your prompt reply and sharing!
