### ISSUE TITLE
图像文本不匹配

### ISSUE THREAD

**Issue by xiaoding06** [Paranioar/RCAR#5]
您好我想问问您论文里面提到的这两个模块，在多模态任务（多模态命名实体识别、多模态情感分析）中存在文本和图像不匹配的情况是否可以使用这两个模块中的其中一个呢？使得图像和文本更加匹配去提升准确度

**Comment by Paranioar** [comment]
> 您好我想问问您论文里面提到的这两个模块，在多模态任务（多模态命名实体识别、多模态情感分析）中存在文本和图像不匹配的情况是否可以使用这两个模块中的其中一个呢？使得图像和文本更加匹配去提升准确度

我觉得试一下就知道啦，哈哈。

**Comment by xiaoding06** [comment]
好的好的非常感谢您的回复，因为刚好做多模态NER任务的时候会出现图像文本不匹配或者图像文本不相关从而影响预测结果的问题，看到了您提到的两个即插即用的模块是关于图像文本匹配问题的模块，所以问问

**Comment by xiaoding06** [comment]
您好我想问问论文里面提到的RCR模块和RAR模块分别是哪个py文件呢？
